### ISSUE TITLE
./generator.py -l md fails to generate the documentation

### ISSUE THREAD

**Issue by ihsandemir** [hazelcast/hazelcast-client-protocol#467]
The documentation generator were broken at [this](https://github.com/hazelcast/hazelcast-client-protocol/commit/9ce557db7eb297629f515275aac92126dbfc2298) commit. It seems to be missing mapping in the functions.

```
➜  hazelcast-client-protocol git:(master) ./generator.py -l md
Hazelcast Client Binary Protocol version 2.6
Traceback (most recent call last):
  File "/Users/ihsan/Desktop/work/src/hazelcast-client-protocol/./generator.py", line 164, in <module>
    env = create_environment(lang, args.namespace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ihsan/Desktop/work/src/hazelcast-client-protocol/util.py", line 700, in create_environment
    for fn_name, fn in language_specific_funcs[lang].items():
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: <SupportedLanguages.MD: 'md'>
➜
```

**Comment by pmcgleenon** [comment]
This should be fixed now
